// Auto-generated by scripts/make_version.sh — do NOT edit.
// Consumed by launcher.rc / FM2KHook/launcher_hook.rc for VERSIONINFO.
// Without this, Windows falls back to the FileDescription from the
// statically-linked libwinpthread runtime ("POSIX WinThreads for
// Windows"), which leaks into Explorer details, the taskbar caption,
// and Shell_NotifyIcon toast titles.
#pragma once

#define FM2K_VER_MAJOR  0
#define FM2K_VER_MINOR  2
#define FM2K_VER_PATCH  42
#define FM2K_VER_BUILD  0
#define FM2K_VER_STRING "0.2.42"
