#!/usr/bin/env bash
# Pre-build version stamper. Writes version_local.h next to it which the
# launcher includes for runtime self-identification ("am I version X?
# is the published LatestVersion newer?"). The semver-style code comes
# from a single FM2K_VERSION line in this script — bump it manually
# when cutting a release. Revision + build-time auto-fill from git.
#
# Invoked as a CMake PRE_BUILD custom command, so version_local.h
# refreshes on every build without requiring a configure step.

set -euo pipefail

# ---- The one line you bump per release ----
FM2K_VERSION="0.1.9"

# ---- Auto-derived ----
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_ROOT/version_local.h"

if git -C "$REPO_ROOT" rev-parse --short HEAD >/dev/null 2>&1; then
    REVISION="$(git -C "$REPO_ROOT" rev-parse --short HEAD)"
    # `git status --porcelain` here was the dirty-check, but on WSL
    # drvfs (Windows-mounted /mnt/c) it stat()'s every tracked file
    # and adds ~30 s per build. Skipped — kAppBuildTime already
    # changes every build so users can tell snapshots apart without
    # the -dirty suffix. Re-enable per-invocation by exporting
    # FM2K_VERSION_DIRTY_CHECK=1.
    if [ -n "${FM2K_VERSION_DIRTY_CHECK:-}" ]; then
        if [ -n "$(git -C "$REPO_ROOT" status --porcelain)" ]; then
            REVISION="${REVISION}-dirty"
        fi
    fi
else
    REVISION="unknown"
fi
BUILD_TIME="$(date -u +'%Y-%m-%d %H:%M UTC')"

cat > "$OUT" <<EOF
// Auto-generated by scripts/make_version.sh — do NOT edit.
// Bump FM2K_VERSION in scripts/make_version.sh to cut a release.
#pragma once

namespace fm2k {

inline constexpr const char* kAppVersion   = "${FM2K_VERSION}";
inline constexpr const char* kAppRevision  = "${REVISION}";
inline constexpr const char* kAppBuildTime = "${BUILD_TIME}";

// GitHub repo hosting public release artifacts. The auto-updater pulls
// LatestVersion from raw.githubusercontent.com/<this>/main and zip
// assets from github.com/<this>/releases/download/v<ver>/...
inline constexpr const char* kUpdateRepoOwner = "Armonte";
inline constexpr const char* kUpdateRepoName  = "fm2ktest";

}  // namespace fm2k
EOF

echo "version_local.h: ${FM2K_VERSION} rev=${REVISION}"
